stages: 
  - mirror
  - build_deploy


mirror:
  stage: mirror
  script:
    - ./ci/mirror.sh
  tags:
    - portfolio

build-portfolio:
  stage: build_deploy
  script:
    - ./ci/build_deploy.sh
  tags:
    - portfolio
