version: "3.4"
services:
  portfolio:
    image: portfolio
    container_name: portfolio
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    restart: always
    ports:
      - "8080:8080"
